/**
 * @fileoverview gRPC-Web generated client stub for IVM.slam
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.2
// source: slam_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')

var pointcloud_pb = require('./pointcloud_pb.js')
const proto = {};
proto.IVM = {};
proto.IVM.slam = require('./slam_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.IVM.slam.SlamServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.IVM.slam.SlamServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.IVM.slam.PointCloud>}
 */
const methodDescriptor_SlamService_GetPointCloud = new grpc.web.MethodDescriptor(
  '/IVM.slam.SlamService/GetPointCloud',
  grpc.web.MethodType.SERVER_STREAMING,
  google_protobuf_empty_pb.Empty,
  pointcloud_pb.PointCloud,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  pointcloud_pb.PointCloud.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.IVM.slam.PointCloud>}
 *     The XHR Node Readable Stream
 */
proto.IVM.slam.SlamServiceClient.prototype.getPointCloud =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/IVM.slam.SlamService/GetPointCloud',
      request,
      metadata || {},
      methodDescriptor_SlamService_GetPointCloud);
};


/**
 * @param {!proto.google.protobuf.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.IVM.slam.PointCloud>}
 *     The XHR Node Readable Stream
 */
proto.IVM.slam.SlamServicePromiseClient.prototype.getPointCloud =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/IVM.slam.SlamService/GetPointCloud',
      request,
      metadata || {},
      methodDescriptor_SlamService_GetPointCloud);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.IVM.slam.PointCloudWithPose>}
 */
const methodDescriptor_SlamService_GetPointCloudWithPose = new grpc.web.MethodDescriptor(
  '/IVM.slam.SlamService/GetPointCloudWithPose',
  grpc.web.MethodType.SERVER_STREAMING,
  google_protobuf_empty_pb.Empty,
  pointcloud_pb.PointCloudWithPose,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  pointcloud_pb.PointCloudWithPose.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.IVM.slam.PointCloudWithPose>}
 *     The XHR Node Readable Stream
 */
proto.IVM.slam.SlamServiceClient.prototype.getPointCloudWithPose =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/IVM.slam.SlamService/GetPointCloudWithPose',
      request,
      metadata || {},
      methodDescriptor_SlamService_GetPointCloudWithPose);
};


/**
 * @param {!proto.google.protobuf.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.IVM.slam.PointCloudWithPose>}
 *     The XHR Node Readable Stream
 */
proto.IVM.slam.SlamServicePromiseClient.prototype.getPointCloudWithPose =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/IVM.slam.SlamService/GetPointCloudWithPose',
      request,
      metadata || {},
      methodDescriptor_SlamService_GetPointCloudWithPose);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.IVM.slam.PoseList>}
 */
const methodDescriptor_SlamService_GetPoses = new grpc.web.MethodDescriptor(
  '/IVM.slam.SlamService/GetPoses',
  grpc.web.MethodType.SERVER_STREAMING,
  google_protobuf_empty_pb.Empty,
  pointcloud_pb.PoseList,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  pointcloud_pb.PoseList.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.IVM.slam.PoseList>}
 *     The XHR Node Readable Stream
 */
proto.IVM.slam.SlamServiceClient.prototype.getPoses =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/IVM.slam.SlamService/GetPoses',
      request,
      metadata || {},
      methodDescriptor_SlamService_GetPoses);
};


/**
 * @param {!proto.google.protobuf.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.IVM.slam.PoseList>}
 *     The XHR Node Readable Stream
 */
proto.IVM.slam.SlamServicePromiseClient.prototype.getPoses =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/IVM.slam.SlamService/GetPoses',
      request,
      metadata || {},
      methodDescriptor_SlamService_GetPoses);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.IVM.slam.SlamData>}
 */
const methodDescriptor_SlamService_GetSlamData = new grpc.web.MethodDescriptor(
  '/IVM.slam.SlamService/GetSlamData',
  grpc.web.MethodType.SERVER_STREAMING,
  google_protobuf_empty_pb.Empty,
  pointcloud_pb.SlamData,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  pointcloud_pb.SlamData.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.IVM.slam.SlamData>}
 *     The XHR Node Readable Stream
 */
proto.IVM.slam.SlamServiceClient.prototype.getSlamData =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/IVM.slam.SlamService/GetSlamData',
      request,
      metadata || {},
      methodDescriptor_SlamService_GetSlamData);
};


/**
 * @param {!proto.google.protobuf.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.IVM.slam.SlamData>}
 *     The XHR Node Readable Stream
 */
proto.IVM.slam.SlamServicePromiseClient.prototype.getSlamData =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/IVM.slam.SlamService/GetSlamData',
      request,
      metadata || {},
      methodDescriptor_SlamService_GetSlamData);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.IVM.slam.SessionInfo>}
 */
const methodDescriptor_SlamService_GetSessionInfo = new grpc.web.MethodDescriptor(
  '/IVM.slam.SlamService/GetSessionInfo',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  pointcloud_pb.SessionInfo,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  pointcloud_pb.SessionInfo.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.IVM.slam.SessionInfo)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.IVM.slam.SessionInfo>|undefined}
 *     The XHR Node Readable Stream
 */
proto.IVM.slam.SlamServiceClient.prototype.getSessionInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/IVM.slam.SlamService/GetSessionInfo',
      request,
      metadata || {},
      methodDescriptor_SlamService_GetSessionInfo,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.IVM.slam.SessionInfo>}
 *     Promise that resolves to the response
 */
proto.IVM.slam.SlamServicePromiseClient.prototype.getSessionInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/IVM.slam.SlamService/GetSessionInfo',
      request,
      metadata || {},
      methodDescriptor_SlamService_GetSessionInfo);
};


module.exports = proto.IVM.slam;

